/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADR_LST_H_RPCGEN
#define _ADR_LST_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct ADR_LST_QUERY_RESULT {
	int success;
	char *result;
};
typedef struct ADR_LST_QUERY_RESULT ADR_LST_QUERY_RESULT;
#ifdef __cplusplus
extern "C" bool_t xdr_ADR_LST_QUERY_RESULT(XDR *, ADR_LST_QUERY_RESULT*);
#elif __STDC__
extern  bool_t xdr_ADR_LST_QUERY_RESULT(XDR *, ADR_LST_QUERY_RESULT*);
#else /* Old Style C */
bool_t xdr_ADR_LST_QUERY_RESULT();
#endif /* Old Style C */

#define ADR_LST_VERS 1

struct adr_lst_auth_1_argument {
	char *username;
	char *passwd;
};
typedef struct adr_lst_auth_1_argument adr_lst_auth_1_argument;
#ifdef __cplusplus
extern "C" bool_t xdr_adr_lst_auth_1_argument(XDR *, adr_lst_auth_1_argument);
#elif __STDC__
extern  bool_t xdr_adr_lst_auth_1_argument(XDR *, adr_lst_auth_1_argument);
#else /* Old Style C */
bool_t xdr_adr_lst_auth_1_argument();
#endif /* Old Style C */


struct adr_lst_query_1_argument {
	int handle;
	int what;
};
typedef struct adr_lst_query_1_argument adr_lst_query_1_argument;
#ifdef __cplusplus
extern "C" bool_t xdr_adr_lst_query_1_argument(XDR *, adr_lst_query_1_argument);
#elif __STDC__
extern  bool_t xdr_adr_lst_query_1_argument(XDR *, adr_lst_query_1_argument);
#else /* Old Style C */
bool_t xdr_adr_lst_query_1_argument();
#endif /* Old Style C */


#define ADR_LST ((u_long)1)
#define ADR_LST_VERS_1 ((u_long)1)

#ifdef __cplusplus
#define ADR_LST_AUTH ((u_long)0)
extern "C" int * adr_lst_auth_1(char , char , CLIENT *);
extern "C" int * adr_lst_auth_1_svc(char , char , struct svc_req *);
#define ADR_LST_QUERY ((u_long)1)
extern "C" ADR_LST_QUERY_RESULT * adr_lst_query_1(int , int , CLIENT *);
extern "C" ADR_LST_QUERY_RESULT * adr_lst_query_1_svc(int , int , struct svc_req *);
#define ADR_LST_LOGOFF ((u_long)2)
extern "C" int * adr_lst_logoff_1(int , CLIENT *);
extern "C" int * adr_lst_logoff_1_svc(int , struct svc_req *);

#elif __STDC__
#define ADR_LST_AUTH ((u_long)0)
extern  int * adr_lst_auth_1(char , char , CLIENT *);
extern  int * adr_lst_auth_1_svc(char , char , struct svc_req *);
#define ADR_LST_QUERY ((u_long)1)
extern  ADR_LST_QUERY_RESULT * adr_lst_query_1(int , int , CLIENT *);
extern  ADR_LST_QUERY_RESULT * adr_lst_query_1_svc(int , int , struct svc_req *);
#define ADR_LST_LOGOFF ((u_long)2)
extern  int * adr_lst_logoff_1(int , CLIENT *);
extern  int * adr_lst_logoff_1_svc(int , struct svc_req *);

#else /* Old Style C */
#define ADR_LST_AUTH ((u_long)0)
extern  int * adr_lst_auth_1();
extern  int * adr_lst_auth_1_svc();
#define ADR_LST_QUERY ((u_long)1)
extern  ADR_LST_QUERY_RESULT * adr_lst_query_1();
extern  ADR_LST_QUERY_RESULT * adr_lst_query_1_svc();
#define ADR_LST_LOGOFF ((u_long)2)
extern  int * adr_lst_logoff_1();
extern  int * adr_lst_logoff_1_svc();
#endif /* Old Style C */

#endif /* !_ADR_LST_H_RPCGEN */
