/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "adr_lst.h"

int *
adr_lst_auth_1_svc(char *username, char *passwd,  struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

ADR_LST_QUERY_RESULT *
adr_lst_query_1_svc(int handle, int what,  struct svc_req *rqstp)
{

	static ADR_LST_QUERY_RESULT  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
adr_lst_logoff_1_svc(int handle,  struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
