/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h>
#include "adr_lst.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
adr_lst_auth_1(char *username, char *passwd,  CLIENT *clnt)
{
	adr_lst_auth_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.username = username;
	arg.passwd = passwd;
	if (clnt_call(clnt, ADR_LST_AUTH, xdr_adr_lst_auth_1_argument, &arg, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

ADR_LST_QUERY_RESULT *
adr_lst_query_1(int handle, int what,  CLIENT *clnt)
{
	adr_lst_query_1_argument arg;
	static ADR_LST_QUERY_RESULT clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.handle = handle;
	arg.what = what;
	if (clnt_call(clnt, ADR_LST_QUERY, xdr_adr_lst_query_1_argument, &arg, xdr_ADR_LST_QUERY_RESULT, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
adr_lst_logoff_1(int handle,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ADR_LST_LOGOFF, xdr_int, &handle, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
