/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "adr_lst.h"


void
adr_lst_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	adr_lst_auth_data  adr_lst_auth_1_arg;
	adr_lst_query_result  *result_2;
	adr_lst_query_data  adr_lst_query_1_arg;
	int  *result_3;
	int  adr_lst_logoff_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADR_LST, ONE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	strcpy((char*) &adr_lst_auth_1_arg.username, "test");
	strcpy((char*) &adr_lst_auth_1_arg.passwd, "test");

	result_1 = adr_lst_auth_1(&adr_lst_auth_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else
	   printf("return value = %d\n",*result_1);
	
	result_2 = adr_lst_query_1(&adr_lst_query_1_arg, clnt);
	if (result_2 == (adr_lst_query_result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = adr_lst_logoff_1(&adr_lst_logoff_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	adr_lst_1 (host);
exit (0);
}
