/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADR_LST_H_RPCGEN
#define _ADR_LST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct adr_lst_auth_data {
	char username[20];
	char passwd[32];
};
typedef struct adr_lst_auth_data adr_lst_auth_data;

struct adr_lst_query_result {
	int error;
	char result[255];
};
typedef struct adr_lst_query_result adr_lst_query_result;

#define ADR_LST 1004711
#define ONE 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADR_LST_AUTH 0
extern  int * adr_lst_auth_1(adr_lst_auth_data *, CLIENT *);
extern  int * adr_lst_auth_1_svc(adr_lst_auth_data *, struct svc_req *);
#define ADR_LST_QUERY 1
extern  adr_lst_query_result * adr_lst_query_1(int *, CLIENT *);
extern  adr_lst_query_result * adr_lst_query_1_svc(int *, struct svc_req *);
#define ADR_LST_LOGOFF 2
extern  int * adr_lst_logoff_1(int *, CLIENT *);
extern  int * adr_lst_logoff_1_svc(int *, struct svc_req *);
extern int adr_lst_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADR_LST_AUTH 0
extern  int * adr_lst_auth_1();
extern  int * adr_lst_auth_1_svc();
#define ADR_LST_QUERY 1
extern  adr_lst_query_result * adr_lst_query_1();
extern  adr_lst_query_result * adr_lst_query_1_svc();
#define ADR_LST_LOGOFF 2
extern  int * adr_lst_logoff_1();
extern  int * adr_lst_logoff_1_svc();
extern int adr_lst_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_adr_lst_auth_data (XDR *, adr_lst_auth_data*);
extern  bool_t xdr_adr_lst_query_result (XDR *, adr_lst_query_result*);

#else /* K&R C */
extern bool_t xdr_adr_lst_auth_data ();
extern bool_t xdr_adr_lst_query_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADR_LST_H_RPCGEN */
