/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "adr_lst.h"
#include "string.h"


int *
adr_lst_auth_1_svc(adr_lst_auth_data *argp, struct svc_req *rqstp)
{
	static int  result;

	sleep(5);

	result = strlen(argp->username) + 100 * strlen(argp->passwd);

	return &result;
}

adr_lst_query_result *
adr_lst_query_1_svc(adr_lst_query_data *argp, struct svc_req *rqstp)
{
	static adr_lst_query_result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
adr_lst_logoff_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
