/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADR_LST_H_RPCGEN
#define _ADR_LST_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct adr_lst_auth_data {
	char username[20];
	char passwd[32];
};
typedef struct adr_lst_auth_data adr_lst_auth_data;
#ifdef __cplusplus
extern "C" bool_t xdr_adr_lst_auth_data(XDR *, adr_lst_auth_data*);
#elif __STDC__
extern  bool_t xdr_adr_lst_auth_data(XDR *, adr_lst_auth_data*);
#else /* Old Style C */
bool_t xdr_adr_lst_auth_data();
#endif /* Old Style C */


struct adr_lst_query_data {
	int handle;
};
typedef struct adr_lst_query_data adr_lst_query_data;
#ifdef __cplusplus
extern "C" bool_t xdr_adr_lst_query_data(XDR *, adr_lst_query_data*);
#elif __STDC__
extern  bool_t xdr_adr_lst_query_data(XDR *, adr_lst_query_data*);
#else /* Old Style C */
bool_t xdr_adr_lst_query_data();
#endif /* Old Style C */


struct adr_lst_query_result {
	int error;
	char result[255];
};
typedef struct adr_lst_query_result adr_lst_query_result;
#ifdef __cplusplus
extern "C" bool_t xdr_adr_lst_query_result(XDR *, adr_lst_query_result*);
#elif __STDC__
extern  bool_t xdr_adr_lst_query_result(XDR *, adr_lst_query_result*);
#else /* Old Style C */
bool_t xdr_adr_lst_query_result();
#endif /* Old Style C */


#define ADR_LST ((u_long)1004711)
#define ONE ((u_long)1)

#ifdef __cplusplus
#define ADR_LST_AUTH ((u_long)0)
extern "C" int * adr_lst_auth_1(adr_lst_auth_data *, CLIENT *);
extern "C" int * adr_lst_auth_1_svc(adr_lst_auth_data *, struct svc_req *);
#define ADR_LST_QUERY ((u_long)1)
extern "C" adr_lst_query_result * adr_lst_query_1(adr_lst_query_data *, CLIENT *);
extern "C" adr_lst_query_result * adr_lst_query_1_svc(adr_lst_query_data *, struct svc_req *);
#define ADR_LST_LOGOFF ((u_long)2)
extern "C" int * adr_lst_logoff_1(int *, CLIENT *);
extern "C" int * adr_lst_logoff_1_svc(int *, struct svc_req *);

#elif __STDC__
#define ADR_LST_AUTH ((u_long)0)
extern  int * adr_lst_auth_1(adr_lst_auth_data *, CLIENT *);
extern  int * adr_lst_auth_1_svc(adr_lst_auth_data *, struct svc_req *);
#define ADR_LST_QUERY ((u_long)1)
extern  adr_lst_query_result * adr_lst_query_1(adr_lst_query_data *, CLIENT *);
extern  adr_lst_query_result * adr_lst_query_1_svc(adr_lst_query_data *, struct svc_req *);
#define ADR_LST_LOGOFF ((u_long)2)
extern  int * adr_lst_logoff_1(int *, CLIENT *);
extern  int * adr_lst_logoff_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define ADR_LST_AUTH ((u_long)0)
extern  int * adr_lst_auth_1();
extern  int * adr_lst_auth_1_svc();
#define ADR_LST_QUERY ((u_long)1)
extern  adr_lst_query_result * adr_lst_query_1();
extern  adr_lst_query_result * adr_lst_query_1_svc();
#define ADR_LST_LOGOFF ((u_long)2)
extern  int * adr_lst_logoff_1();
extern  int * adr_lst_logoff_1_svc();
#endif /* Old Style C */

#endif /* !_ADR_LST_H_RPCGEN */
