/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "adr_lst.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
adr_lst_auth_1(argp, clnt)
	adr_lst_auth_data *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ADR_LST_AUTH, xdr_adr_lst_auth_data, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

adr_lst_query_result *
adr_lst_query_1(argp, clnt)
	adr_lst_query_data *argp;
	CLIENT *clnt;
{
	static adr_lst_query_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ADR_LST_QUERY, xdr_adr_lst_query_data, argp, xdr_adr_lst_query_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
adr_lst_logoff_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ADR_LST_LOGOFF, xdr_int, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
