/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "adr_lst.h"

bool_t
xdr_adr_lst_auth_data (XDR *xdrs, adr_lst_auth_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->username, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->passwd, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_adr_lst_query_result (XDR *xdrs, adr_lst_query_result *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->result, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
