/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "adr_lst.h"


void
adr_lst_1( char* host )
{
	CLIENT *clnt;
	int  *result_1;
	char  adr_lst_auth_1_username;
	char  adr_lst_auth_1_passwd;
	ADR_LST_QUERY_RESULT  *result_2;
	int  adr_lst_query_1_handle;
	int  adr_lst_query_1_what;
	int  *result_3;
	int  adr_lst_logoff_1_handle;
	clnt = clnt_create(host, ADR_LST, ADR_LST_VERS_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = adr_lst_auth_1(adr_lst_auth_1_username, adr_lst_auth_1_passwd, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = adr_lst_query_1(adr_lst_query_1_handle, adr_lst_query_1_what, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_3 = adr_lst_logoff_1(adr_lst_logoff_1_handle, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	adr_lst_1( host );
}
